DL-12454-Play3.0 Upgrade- Single Commit with all changes
hmrc/ated-subscription-frontend pull request #183
Opened 2024-04-04 13:28 UTC by rameshmandanapu1

# JIRA Story or Github Number - descriptive title

**Bug fix / New feature** (delete as appropriate)

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

## Checklist

*Reviewee* (Replace with your name)
 - [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [ ]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

*Reviewer* (Replace with your name)
 - [ ]  I've confirmed that every effort has been made to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've confirmed appropriate tests has been included with any code added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [ ]  I've confirmed code was added using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

2024-04-05 07:17 UTC, paulanderson1234 commented
There is almost certainly a few things that could be removed here based on recently reviewed changes to ACM and ATED FE upgrades. We may be able to 

- remove TestPhases file if removed from build.sbt
- remove mockito-core, mockito-4-11, and jackson modules as bootstrap comes with a version that may suffice for tests
- remove it dependency as we have found somewhere in IntegrationBase (or similar) it will import wiremock from tomakehurst (therefore rendering the one we have updated as not required)
- need to check if akka.stream is present in logback file as this probably needs updating to org.apache.pekko.stream

2024-04-05 07:55 UTC, rameshmandanapu1 commented
.settings(inConfig(TemplateTest )(Defaults.testSettings) *) is calling testphases from build.sbt file, Unable to remove.

2024-04-05 09:39 UTC, benryan1790 requested changes

2024-04-05 09:39 UTC, benryan1790 commented on project/AppDependencies.scala
> +    "org.wiremock" % "wiremock" % "3.4.2" % Test
This needs to be removed, with it in the it tests do not work

2024-04-05 09:39 UTC, benryan1790 commented on app/controllers/ApplicationController.scala
> +  def cancel: Action[AnyContent] = Action { implicit _ =>
Why were these changed?

2024-04-08 10:53 UTC, rameshmandanapu1 commented
> * .settings(inConfig(TemplateTest )(Defaults.testSettings) *) is calling testphases from build.sbt file, Unable to remove.
> 
>     * getting below error when removing Jackson dependency - com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.14.3 requires Jackson Databind version >= 2.14.0 and < 2.15.0 - Found jackson-databind version 2.16.1

2024-04-08 11:32 UTC, merged